"""Pre-loaded demo reports for the GlycoHerb-DS project."""

def DEMO_REPORTS(main_pid, res_id, t):
    return [
        ('disease_intel',
         {'disease':'Type 2 Diabetes Mellitus','healthcare_problem':'Affordable herbal anti-diabetic for rural India','target_population':'Adults 40-70 rural India'},
         {"disease_overview":{"name":"Type 2 Diabetes Mellitus","icd_code":"E11","category":"Metabolic disorder","description":"T2DM is a chronic metabolic disorder affecting 537 million adults globally. India has 77 million diabetic patients. Characterised by insulin resistance and progressive beta-cell dysfunction leading to hyperglycaemia."},"epidemiology":{"global_prevalence":"537 million adults (IDF 2021)","incidence_rate":"6.96 million new cases/year in India","mortality_rate":"6.7 million deaths/year globally","geographic_hotspots":["India","China","USA","Pakistan","Brazil"],"high_risk_groups":["Adults 45+","Overweight/obese","Family history","Sedentary lifestyle","South Asian ethnicity"]},"opportunity_analysis":{"market_size_estimate":"USD 58.6 billion (2023)","growth_rate_cagr":"5.1%","opportunity_score":9,"opportunity_rationale":"Massive unmet need for affordable herbal alternatives. India AYUSH push creates regulatory tailwind.","key_value_drivers":["77 million patients in India","Government AYUSH promotion","Patient preference for natural therapies","Low raw material cost"]},"innovation_suggestions":[{"title":"GlycoHerb-DS: Bitter Melon + Fenugreek Tablet","approach":"4-herb standardised combination in film-coated tablet","novelty_level":"significant","feasibility":"high","time_to_market_years":3},{"title":"Gymnema Nanoemulsion","approach":"Enhanced bioavailability formulation","novelty_level":"breakthrough","feasibility":"medium","time_to_market_years":5}],"confidence_level":"high","analyst_notes":"Strong commercial opportunity. Recommend Ayurvedic route for faster approval."},
         1847),
        ('formulation_intel',
         {'disease':'Type 2 Diabetes','product_type':'Ayurvedic','dosage_form':'Tablet'},
         {"product_overview":{"proposed_name":"GlycoHerb-DS Tablet","category":"Ayurvedic Proprietary Medicine","route_of_administration":"Oral","target_patient_profile":"Adult T2DM patients 40-70 years"},"active_ingredients":[{"name":"Bitter Melon Dry Extract","pharmacological_class":"Alpha-glucosidase inhibitor","dose_per_unit":"250 mg","role_in_formulation":"primary"},{"name":"Fenugreek Seed Extract","pharmacological_class":"Insulin sensitiser","dose_per_unit":"125 mg","role_in_formulation":"primary"},{"name":"Gymnema sylvestre Extract","pharmacological_class":"Beta-cell regenerator","dose_per_unit":"100 mg","role_in_formulation":"adjuvant"},{"name":"Amla Extract","pharmacological_class":"Antioxidant","dose_per_unit":"50 mg","role_in_formulation":"adjuvant"}],"excipients":[{"name":"MCC PH102","category":"diluent","quantity_per_unit":"150 mg","function":"Primary filler","grade":"Ph.Eur"},{"name":"Croscarmellose Sodium","category":"disintegrant","quantity_per_unit":"20 mg","function":"Super-disintegrant","grade":"NF"},{"name":"Magnesium Stearate","category":"lubricant","quantity_per_unit":"5 mg","function":"Lubricant","grade":"Ph.Eur"}],"batch_formula":{"batch_size":"100,000 tablets","theoretical_yield":"98,500 tablets","total_weight_per_unit":"743 mg"},"manufacturing_method":{"primary_process":"Wet Granulation → Fluid Bed Drying → Compression → Film Coating","critical_steps":["Granulation endpoint","LOD <3%","Blend uniformity RSD <2%","Hardness 6-10 kP"],"equipment_required":["High-shear granulator 300L","Fluid bed dryer","Rotary compression machine","Pan coater"]},"packaging_recommendation":{"primary_pack":"Alu-Alu blister","storage_conditions":"Below 30°C, protect from moisture","shelf_life_estimate":"24 months"}},
         2341),
        ('literature_intel',
         {'topic':'Momordica charantia Fenugreek diabetes RCT','year_range':'2019-2024'},
         {"topic_overview":{"standardised_topic":"Herbal medicines in Type 2 Diabetes","mesh_terms":["Diabetes Mellitus Type 2","Phytotherapy","Momordica charantia","Trigonella foenum-graecum"],"field_maturity":"developing"},"literature_review":{"summary":"Strong evidence base: 23 human studies, 3 meta-analyses. Mean HbA1c reduction 0.82% vs placebo for Bitter Melon. Fenugreek shows FBG reduction 17.6 mg/dL. Excellent safety profiles.","total_studies_estimated":"4,200+ (PubMed 2019-2024)","key_findings":["Bitter Melon reduces HbA1c 0.82% vs placebo (18 RCTs)","Fenugreek reduces FBG 17.6 mg/dL (26 RCTs)","Gymnema shows beta-cell regenerating activity","No serious adverse events in 2000+ patient-years"]},"key_studies":[{"title":"Bitter melon reduces HbA1c: systematic review","authors":"Fuangchan A et al.","year":"2022","journal":"J Ethnopharmacology","evidence_level":"I","key_finding":"HbA1c reduction 0.82% (95% CI 0.61-1.03)"},{"title":"Trigonella foenum-graecum meta-analysis","authors":"Neelakantan N et al.","year":"2021","journal":"Nutrition Reviews","evidence_level":"I","key_finding":"FBG reduction 17.6 mg/dL, HbA1c -0.85%"}],"research_gaps":[{"gap":"No RCT comparing 4-herb combination vs metformin","priority":"high"},{"gap":"Long-term safety data beyond 12 months","priority":"medium"}],"research_summary":{"strength_of_evidence":"moderate","state_of_evidence":"Level I for individual herbs"}},
         1523),
        ('regulatory_intel',
         {'disease':'Type 2 Diabetes','product_type':'Ayurvedic','target_markets':['CDSCO','AYUSH']},
         {"product_classification":{"category":"Ayurvedic Proprietary Medicine","drug_type":"Herbal","schedule_india":"Schedule E(1)"},"regulatory_pathways":[{"authority":"CDSCO/AYUSH","pathway":"Form 26-D New Ayurvedic Drug License","estimated_timeline_months":18,"estimated_cost_usd":"USD 15,000-30,000","key_requirements":["AYUSH GMP Certificate","Safety & efficacy data","Herbs in Ayurvedic Pharmacopoeia","Stability data","Heavy metals testing"]}],"compliance_checklist":[{"item":"AYUSH GMP Certificate","category":"Quality","mandatory":True},{"item":"Heavy metals testing (As, Pb, Hg, Cd)","category":"Safety","mandatory":True},{"item":"Stability study 6 months accelerated","category":"Quality","mandatory":True},{"item":"Clinical evidence (3+ RCTs or pilot study)","category":"Efficacy","mandatory":True}],"timeline_overview":{"total_estimated_months":30,"key_milestones":["Month 3: GMP audit","Month 6: Stability initiation","Month 12: Submission","Month 30: License grant"]},"consultant_notes":"AYUSH route optimal — faster and less expensive than allopathic approval."},
         1986),
        ('dossier',
         {'disease':'Type 2 Diabetes','product_name':'GlycoHerb-DS Tablet','dosage_form':'Film-Coated Tablet','product_type':'Ayurvedic'},
         {"dossier_overview":{"product_name":"GlycoHerb-DS Tablet","inn_or_common_name":"Momordica charantia + Trigonella foenum-graecum + Gymnema sylvestre + Emblica officinalis","dosage_form":"Film-Coated Tablet","route":"Oral","dossier_type":"Ayurvedic New Drug — Form 26-D"},"executive_summary":"GlycoHerb-DS Tablet is a scientifically designed Ayurvedic proprietary medicine for adjunct management of Type 2 Diabetes Mellitus. The product combines four synergistic herbs each standardised to established markers. Clinical evidence base: 23 published studies including 3 meta-analyses with Level I evidence. Safety: no serious adverse events across 2000+ patient-years. Regulatory pathway: AYUSH Form 26-D, estimated 30 months to approval. Target: 77 million T2DM patients in India.","module_2_summaries":{"quality_overall_summary":"Validated wet granulation process. All excipients pharmacopoeial grade. 6-month accelerated stability data shows full compliance.","nonclinical_overview":"Acute oral LD50 >5000 mg/kg for all extracts. Ames test negative. 28-day repeat dose NOAEL established.","clinical_overview":"23 human studies reviewed. Mean HbA1c reduction 0.62-0.85% vs placebo. Excellent safety profile."},"submission_readiness":{"completed_sections":["Module 2 summaries","Module 3 CMC","Module 4 nonclinical","Module 5 literature evidence"],"sections_requiring_data":["Pilot clinical study (60 patients)","Real-time stability 12/24 months","Site Master File"],"estimated_completion_timeline":"12 months","critical_path_items":["60-patient pilot RCT (9 months)","AYUSH GMP certificate (3 months)"]}},
         3102),
    ]
